Data:
    data_keys: ['PEMS03', 'PEMS04', 'PEMS07', 'PEMS08']
    node_keys: [358, 307, 883, 170]
    node_city: 
        358: 'PEMS03' 
        307: 'PEMS04' 
        883: 'PEMS07' 
        170: 'PEMS08'
PEMS03:
    adj_filename: ./data/PEMS03/PEMS03.csv
    graph_signal_matrix_filename: ./data/PEMS03/PEMS03.npz
    stag_filename: ./data/PEMS03/stag_001_PEMS03.csv
    id_filename: ./data/PEMS03/PEMS03.txt
    strg_filename: ./data/PEMS03/strg_001_PEMS03.csv
    num_of_vertices: 358
    period: 288
    points_per_hour: 12
    num_for_predict: 12
    len_input: 
    dataset_name: PEMS03
PEMS04:
    adj_filename: ./data/PEMS04/PEMS04.csv
    graph_signal_matrix_filename: ./data/PEMS04/PEMS04.npz
    stag_filename: ./data/PEMS04/stag_001_PEMS04.csv
    strg_filename: ./data/PEMS04/strg_001_PEMS04.csv
    num_of_vertices: 307
    period: 288
    points_per_hour: 12
    num_for_predict: 12
    len_input: 12
    dataset_name: PEMS04
PEMS07:
    adj_filename: ./data/PEMS07/PEMS07.csv
    graph_signal_matrix_filename: ./data/PEMS07/PEMS07.npz
    stag_filename: ./data/PEMS07/stag_001_PEMS07.csv
    strg_filename: ./data/PEMS07/strg_001_PEMS07.csv
    num_of_vertices: 883
    period: 288
    points_per_hour: 12
    num_for_predict: 12
    len_input: 12
    dataset_name: PEMS07
PEMS08:
    adj_filename: ./data/PEMS08/PEMS08.csv
    graph_signal_matrix_filename: ./data/PEMS08/PEMS08.npz
    stag_filename: ./data/PEMS08/stag_001_PEMS08.csv
    strg_filename: ./data/PEMS08/strg_001_PEMS08.csv
    num_of_vertices: 170
    period: 288
    points_per_hour: 12
    num_for_predict: 12
    len_input: 12
    dataset_name: PEMS08


Training:
    ctx: '0'
    in_channels: 1
    nb_block: 4
    n_heads: 3
    K: 3
    d_k: 32
    nb_chev_filter: 32
    nb_time_filter: 32
    d_model: 256
    batch_size: 64
    points_per_hour: 12
    num_for_predict: 12
    len_input: 12
    model_name: three-378
    num_of_weeks: 0
    num_of_days: 0
    num_of_hours: 1
    start_epoch: 0
    epochs: 1
    learning_rate: 0.0001
    graph: AG
#[90,110,30,100]
#['PEMS03', 'PEMS04', 'PEMS07', 'PEMS08']
#[358, 307, 883, 170]